import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

ThemeData lightTheme = ThemeData(
  useMaterial3: true,
  colorScheme: lightColorScheme,
  textTheme: const TextTheme(),
  fontFamily: GoogleFonts.cinzel().fontFamily,
  tooltipTheme: TooltipThemeData(
    textStyle: TextStyle(
      color: lightColorScheme.onPrimaryContainer,
    ),
    decoration: BoxDecoration(
      borderRadius: BorderRadius.circular(10),
      color: lightColorScheme.primaryContainer,
    ),
  ),
);
ThemeData darkTheme = ThemeData(
  useMaterial3: true,
  colorScheme: darkColorScheme,
  textTheme: const TextTheme(),
  fontFamily: GoogleFonts.cinzel().fontFamily,
  tooltipTheme: TooltipThemeData(
    textStyle: TextStyle(
      color: darkColorScheme.onPrimaryContainer,
    ),
    decoration: BoxDecoration(
      borderRadius: BorderRadius.circular(10),
      color: darkColorScheme.primaryContainer,
    ),
  ),
);
const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFFBD0C2C),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFFFDAD8),
  onPrimaryContainer: Color(0xFF410008),
  secondary: Color(0xFF6E4EA1),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFECDCFF),
  onSecondaryContainer: Color(0xFF270057),
  tertiary: Color(0xFF9C404C),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFFFDADB),
  onTertiaryContainer: Color(0xFF40000E),
  error: Color(0xFFBA1A1A),
  errorContainer: Color(0xFFFFDAD6),
  onError: Color(0xFFFFFFFF),
  onErrorContainer: Color(0xFF410002),
  background: Color(0xFFFFFBFF),
  onBackground: Color(0xFF40000E),
  surface: Color(0xFFFFFBFF),
  onSurface: Color(0xFF40000E),
  surfaceVariant: Color(0xFFF4DDDC),
  onSurfaceVariant: Color(0xFF524343),
  outline: Color(0xFF857372),
  onInverseSurface: Color(0xFFFFECED),
  inverseSurface: Color(0xFF5F1220),
  inversePrimary: Color(0xFFFFB3B1),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFBD0C2C),
  outlineVariant: Color(0xFFD7C1C0),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFFFB3B1),
  onPrimary: Color(0xFF680012),
  primaryContainer: Color(0xFF92001E),
  onPrimaryContainer: Color(0xFFFFDAD8),
  secondary: Color(0xFFD6BAFF),
  onSecondary: Color(0xFF3E1C6F),
  secondaryContainer: Color(0xFF553587),
  onSecondaryContainer: Color(0xFFECDCFF),
  tertiary: Color(0xFFFFB2B8),
  onTertiary: Color(0xFF5F1220),
  tertiaryContainer: Color(0xFF7D2935),
  onTertiaryContainer: Color(0xFFFFDADB),
  error: Color(0xFFFFB4AB),
  errorContainer: Color(0xFF93000A),
  onError: Color(0xFF690005),
  onErrorContainer: Color(0xFFFFDAD6),
  background: Color(0xFF40000E),
  onBackground: Color(0xFFFFDADB),
  surface: Color(0xFF40000E),
  onSurface: Color(0xFFFFDADB),
  surfaceVariant: Color(0xFF524343),
  onSurfaceVariant: Color(0xFFD7C1C0),
  outline: Color(0xFFA08C8B),
  onInverseSurface: Color(0xFF40000E),
  inverseSurface: Color(0xFFFFDADB),
  inversePrimary: Color(0xFFBD0C2C),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFFFB3B1),
  outlineVariant: Color(0xFF524343),
  scrim: Color(0xFF000000),
);
